#!/bin/bash

# dont think this works atm
# TODO: investigate

windowtitlev2() {
  IFS=',' read -r -a args <<< "$1"
  args[0]="${args[0]#*>>}"

  if [[ ${args[1]} == "Tillägg: (Bitwarden Lösenordshanterare) - Bitwarden — Ursprunglig profil — Mozilla Firefox" ]]; then
    hyprctl --batch "\
      dispatch setfloating address:0x${args[0]}; \
      dispatch resizewindowpixel exact 430 560, address:0x${args[0]}; \
      dispatch centerwindow; \
    "
  fi
}

handle() {
  case $1 in
    windowtitlev2\>*) windowtitlev2 "$1" ;;
  esac
}

socat -U - UNIX-CONNECT:"/$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" \
  | while read -r line; do handle "$line"; done
