#!/bin/bash

CONFIG_FILES="$XDG_CONFIG_HOME/waybar/config.jsonc $XDG_CONFIG_HOME/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
