export KUBECONFIG="$XDG_CONFIG_HOME/kube.yaml"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export NPM_CONFIG_CACHE="$XDG_CONFIG_HOME/npm"
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible.cfg"
# export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export SBT_OPTS="-Dsbt.global.base=$XDG_DATA_HOME/sbt/1.0 -Dsbt.boot.directory=$XDG_CACHE_HOME/sbt/boot -Dsbt.repository.config=$XDG_CACHE_HOME/sbt/repositories -Dsbt.ivy.home=$XDG_CACHE_HOME/ivy2"

export GHCUP_USE_XDG_DIRS=1
export STACK_XDG=1
export STACK_ROOT="$XDG_DATA_HOME/stack"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export PNPM_HOME="$XDG_DATA_HOME/pnpm"
export ANSIBLE_HOME="$XDG_DATA_HOME/ansible"
export DOTNET_CONFIG="$XDG_DATA_HOME/dotnet"
export DOTNET_CLI_HOME="$XDG_DATA_HOME/dotnet"
export DOTNET_TOOLS_PATH="$XDG_DATA_HOME/dotnet/tools"
export WINEPREFIX="$XDG_DATA_HOME/wine"
export KUBECACHEDIR="$XDG_CACHE_HOME/kube"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:"
export JULIAUP_DEPOT_PATH="$XDG_DATA_HOME/julia"
export SONARLINT_USER_HOME="$XDG_DATA_HOME/sonarlint"
export LEIN_HOME="$XDG_DATA_HOME/lein"
export GOPATH="$XDG_DATA_HOME/go"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export ZSH="$XDG_DATA_HOME/oh-my-zsh"

export PYTHON_HISTORY="$XDG_STATE_HOME/python_history"
export TS_NODE_HISTORY="$XDG_STATE_HOME/ts_node_repl_history"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"
