return {
  -- 'miversen33/sunglasses.nvim',
  -- opts = {
  --   filter_percent = 0.2,
  --   excluded_filetypes = {
  --     'checkhealth',
  --     'mason',
  --     'plugin',
  --     'lazy',
  --     'DiffviewFiles',
  --     'DiffviewFileHistory',
  --     'DressingInput',
  --     'zsh',
  --     'registers',
  --     'noice',
  --     'notify',
  --     'snacks_picker_list',
  --     'snacks_picker_input',
  --     'snacks_picker_preview',
  --     'trouble',
  --   },
  --   excluded_highlights = {
  --     'TodoFgTODO',
  --   },
  -- },
}
